
data:
  subjects:
    - EC243
    - EC248
    - EC250
    - EC253
    - EC260
    - EC270
    - EC278
    - EC279
    # - EC282 # missing ecog data

run_notebooks:
  mismatch_erp:
  population_decoding:
  population_decoding_nopca:
    notebook: population_decoding
    params:
      pca_num_components: null
  population_decoding_speech_responsive: