
data:
  subjects:
    - EC243
    - EC248
    - EC250
    - EC253
    - EC260
    - EC270
    - EC278
    - EC279
    - EC282
    - EC287

run_notebooks:
  mismatch_erp:
  population_decoding:
  population_decoding_nopca:
    notebook: population_decoding
    params:
      pca_num_components: null
  population_decoding_speech_responsive:


decoding:
  targets:
    - acoustic
    - mismatch
    - lexical_evidence
    - mismatch_left_right
    - behavior_categorical

  num_random_runs: 3

  window_sizes:
    # - 10
    # - 20
    - 30
    # - 60
    # - 90
    # - 120